export const albumConstants = {
  ALBUM_CREATE_REQUEST: "ALBUM_CREATE_REQUEST",
  ALBUM_CREATE_SUCCESS: "ALBUM_CREATE_SUCCESS",
  ALBUM_CREATE_FAILURE: "ALBUM_CREATE_FAILURE",

  ALBUM_GETALL_REQUEST: "ALBUM_GETALL_REQUEST",
  ALBUM_GETALL_SUCCESS: "ALBUM_GETALL_SUCCESS",
  ALBUM_GETALL_FAILURE: "ALBUM_GETALL_FAILURE",

  ALBUM_GETBYID_REQUEST: "ALBUM_GETBYID_REQUEST",
  ALBUM_GETBYID_SUCCESS: "ALBUM_GETBYID_SUCCESS",
  ALBUM_GETBYID_FAILURE: "ALBUM_GETBYID_FAILURE",

  ALBUM_UPDATE_REQUEST: "ALBUM_UPDATE_REQUEST",
  ALBUM_UPDATE_SUCCESS: "ALBUM_UPDATE_SUCCESS",
  ALBUM_UPDATE_FAILURE: "ALBUM_UPDATE_FAILURE",

  ALBUM_DELETE_REQUEST: "ALBUM_DELETE_REQUEST",
  ALBUM_DELETE_SUCCESS: "ALBUM_DELETE_SUCCESS",
  ALBUM_DELETE_FAILURE: "ALBUM_DELETE_FAILURE"
}
