export const playlistConstants = {
  PLAYLIST_CREATE_REQUEST: "PLAYLIST_CREATE_REQUEST",
  PLAYLIST_CREATE_SUCCESS: "PLAYLIST_CREATE_SUCCESS",
  PLAYLIST_CREATE_FAILURE: "PLAYLIST_CREATE_FAILURE",

  PLAYLIST_UPDATE_REQUEST: "PLAYLIST_UPDATE_REQUEST",
  PLAYLIST_UPDATE_SUCCESS: "PLAYLIST_UPDATE_SUCCESS",
  PLAYLIST_UPDATE_FAILURE: "PLAYLIST_UPDATE_FAILURE",

  PLAYLIST_GETBYID_REQUEST: "PLAYLIST_GETBYID_REQUEST",
  PLAYLIST_GETBYID_SUCCESS: "PLAYLIST_GETBYID_SUCCESS",
  PLAYLIST_GETBYID_FAILURE: "PLAYLIST_GETBYID_FAILURE",

  PLAYLIST_GETALL_REQUEST: "PLAYLIST_GETALL_REQUEST",
  PLAYLIST_GETALL_SUCCESS: "PLAYLIST_GETALL_SUCCESS",
  PLAYLIST_GETALL_FAILURE: "PLAYLIST_GETALL_FAILURE",

  PLAYLIST_DELETE_REQUEST: "PLAYLIST_DELETE_REQUEST",
  PLAYLIST_DELETE_SUCCESS: "PLAYLIST_DELETE_SUCCESS",
  PLAYLIST_DELETE_FAILURE: "PLAYLIST_DELETE_FAILURE"
}
