export const songConstants = {
  SONG_CREATE_REQUEST: "SONG_CREATE_REQUEST",
  SONG_CREATE_SUCCESS: "SONG_CREATE_SUCCESS",
  SONG_CREATE_FAILURE: "SONG_CREATE_FAILURE",

  SONG_UPDATE_REQUEST: "SONG_UPDATE_REQUEST",
  SONG_UPDATE_SUCCESS: "SONG_UPDATE_SUCCESS",
  SONG_UPDATE_FAILURE: "SONG_UPDATE_FAILURE",

  SONG_GETBYID_REQUEST: "SONG_GETBYID_REQUEST",
  SONG_GETBYID_SUCCESS: "SONG_GETBYID_SUCCESS",
  SONG_GETBYID_FAILURE: "SONG_GETBYID_FAILURE",

  SONG_GETALL_REQUEST: "SONG_GETALL_REQUEST",
  SONG_GETALL_SUCCESS: "SONG_GETALL_SUCCESS",
  SONG_GETALL_FAILURE: "SONG_GETALL_FAILURE",

  SONG_DELETE_REQUEST: "SONG_DELETE_REQUEST",
  SONG_DELETE_SUCCESS: "SONG_DELETE_SUCCESS",
  SONG_DELETE_FAILURE: "SONG_DELETE_FAILURE"
}
